8260339: JVM crashes when executing PhaseIdealLoop::match_fill_loop
openjdk/jdk16 pull request #132
Opened 2021-01-26 02:01 UTC by Wanghuang-Huawei

The reason is :

```
  BasicType t = store->as_Mem()->memory_type();
  const char* fill_name;
  if (msg == NULL &&
      StubRoutines::select_fill_function(t, false, fill_name) == NULL) {
    msg = "unsupported store";
    msg_node = store;
  }
```

If the `store` is a `StoreVectorNode` ,the `BasicType` is `T_VOID`. We should get the basic type from `vect_type()->element_basic_type()` .

```
- BasicType t = store->as_Mem()->memory_type();
+ BasicType t;
+ if (store->is_StoreVector()) {
+ t = store->as_StoreVector()->vect_type()->element_basic_type();
+ } else {
+ t = store->as_Mem()->memory_type();
+ }
```

2021-01-26 02:21 UTC, Wanghuang-Huawei commented
/contributor add He Xuejin <hexuejin2@huawei.com>

2021-01-26 09:28 UTC, neliasso reviewed
The fix looks good.

Since JDK 16 is in rampdown phase 2 (http://openjdk.java.net/jeps/3) - this fix will need additional approval before it can be pushed. I will help out with that.

2021-01-26 09:38 UTC, Wanghuang-Huawei commented
> The fix looks good.
> 
> Since JDK 16 is in rampdown phase 2 (http://openjdk.java.net/jeps/3) - this fix will need additional approval before it can be pushed. I will help out with that.

Thank you for your review and help.

2021-01-26 12:07 UTC, DamonFool commented
Hi @Wanghuang-Huawei , I'm still not clear how to reproduce the bug.

Is it possible to add a jtreg test for this fix?
Thanks.

2021-01-26 17:16 UTC, vnkozlov requested changes
Need regression test since change is in common code.

2021-01-26 18:24 UTC, iignatev commented
Hi @Wanghuang-Huawei,

given JDK16 is RDP2 and your patch changes the shared code, you are to integrate an automated jtreg test together with the fix. I've taken `TestLoopStoreVector.java` from 8260339 and added the minimal required jtreg test description, and double-checked that the test fails on linux-aarch64 w/o the fix and passes w/ it. you can take the jtreg-ified test in my [pull/132](https://github.com/iignatev/jdk16/tree/pull/132) branch (you will need to replace `$copyright-header` w/ the appropriate line), feel free to use it as-is or modify.

Thanks,
-- Igor

2021-01-26 18:42 UTC, iignatev commented
/cc hotspot-compiler

2021-01-26 23:45 UTC, DamonFool commented
> Hi @Wanghuang-Huawei , I'm still not clear how to reproduce the bug.
> 

Ah, I missed the attachment in the JBS.
Thumbs-up @Wanghuang-Huawei .

2021-01-27 09:02 UTC, Wanghuang-Huawei commented
> Hi @Wanghuang-Huawei,
> 
> given JDK16 is RDP2 and your patch changes the shared code, you are to integrate an automated jtreg test together with the fix. I've taken `TestLoopStoreVector.java` from 8260339 and added the minimal required jtreg test description, and double-checked that the test fails on linux-aarch64 w/o the fix and passes w/ it. you can take the jtreg-ified test from my [pull/132](https://github.com/iignatev/jdk16/tree/pull/132) branch (you will need to replace `$copyright-header` w/ the appropriate line), feel free to use it as-is or modify.
> 
> Thanks,
> -- Igor

Thank you very much. I will push a new commit which contains jtreg test.

2021-01-27 10:22 UTC, neliasso commented
@Wanghuang-Huawei Have you been able to reproduce this on any other platform that linux-aarch64? I'm having trouble reproducing this on x64.

2021-01-27 10:38 UTC, DamonFool commented
> @Wanghuang-Huawei Have you been able to reproduce this on any other platform that linux-aarch64? I'm having trouble reproducing this on x64.

I tried the reproducer on the JBS just now and couldn't reproduce it on x64 either.

2021-01-27 10:39 UTC, nsjian commented
> @Wanghuang-Huawei Have you been able to reproduce this on any other platform that linux-aarch64? I'm having trouble reproducing this on x64.

I think x64 has disabled OptimizeFill by default. I can reproduce this with -XX:+OptimizeFill.

2021-01-27 11:10 UTC, neliasso commented
Please add  -XX:+OptimizeFill to the regression test

2021-01-27 17:23 UTC, vnkozlov commented
Yes, OptimizeFill  is off after 8247307 changes in JDK 16. Add it to @run command (it is C2 flag so you need `Ignore*` flag):
```
* @run main/othervm -XX:+IgnoreUnrecognizedVMOptions -XX:+OptimizeFill
```

2021-01-28 01:57 UTC, vnkozlov commented on test/hotspot/jtreg/compiler/vectorapi/TestLoopStoreVector.java
> + * @run main/othervm -XX:+IgnoreUnrecognizedVMOptions -XX:+OptimizeFill
You forgot test name

2021-01-28 02:39 UTC, vnkozlov approved these changes
Good.
Wait an other day for other people to look.

2021-01-28 02:45 UTC, iignatev approved these changes
LGTM

2021-01-28 06:06 UTC, Wanghuang-Huawei commented
/integrate

2021-01-28 11:33 UTC, neliasso approved these changes
Looks good.

2021-01-28 11:36 UTC, neliasso commented
I will sponsor this change when 24 hours have passed since the last update.

2021-01-29 08:06 UTC, neliasso commented
/sponsor

2021-01-29 08:07 UTC, closed without merging